### ISSUE TITLE
Default ordering in example does not match that of splncs04

### ISSUE THREAD

**Issue by tvercaut** [mgttlinger/biblatex-lncs#11]
The basic usage
https://github.com/mgttlinger/biblatex-lncs#usage
and example
https://github.com/mgttlinger/biblatex-lncs/blob/1ddaef8f311a06e43b2186a9446761a5e0103cf9/biblatex-lncs-test.tex#L3
do not end up with the same order as splncs04.

For ease of use, it would be good to align this with the splncs04 behaviour. I believe this can be done by adding `sorting=nyt` to the package options.

**Comment by mgttlinger** [comment]
I think I'd rather leave the sorting unchanged as the file is not a usage example but rather a file for testing the style output where it is much easier to have no automatic sorting and append new test cases at the end. The usage example in the Readme doesn't include the `sorting=none` so that should be fine, right?

**Comment by tvercaut** [comment]
Thanks. That's correct re "basic usage" notes. I hadn't tried removing `sorting=none` and (wrongly) assumed this was the default. A quick test seems to indicate that the default is appropriate.

I also understand the rationale for the test case.
